// Generated by rstantools.  Do not edit by hand.

/*
    bsem is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bsem is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bsem.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_semNAEX_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_semNAEX");
    reader.add_event(152, 150, "end", "model_semNAEX");
    return reader;
}
#include <stan_meta_header.hpp>
class model_semNAEX
  : public stan::model::model_base_crtp<model_semNAEX> {
private:
        int K;
        int Nv;
        int Ne;
        int Ny;
        std::vector<int> idyi;
        std::vector<int> idy;
        std::vector<int> nbeta;
        std::vector<int> idlamb;
        int Nob;
        int Nna;
        matrix_d X;
        std::vector<std::vector<int> > idob;
        std::vector<std::vector<int> > idna;
        int Nex;
        std::vector<int> ngamma;
        std::vector<int> idexi;
        std::vector<int> idex;
        std::vector<int> idlambex;
        std::vector<int> asc;
        matrix_d v;
        std::vector<double> dsigma2;
        std::vector<double> a;
        std::vector<double> b;
        std::vector<double> dtau2;
        std::vector<double> at;
        std::vector<double> bt;
        std::vector<double> dbeta;
        std::vector<double> m;
        std::vector<double> s;
        std::vector<double> dgamma;
        std::vector<double> mg;
        std::vector<double> sg;
        std::vector<double> dgamma0;
        std::vector<double> mg0;
        std::vector<double> sg0;
public:
    model_semNAEX(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_semNAEX(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_semNAEX_namespace::model_semNAEX";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            check_greater_or_equal(function__, "K", K, 1);
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "Nv", "int", context__.to_vec());
            Nv = int(0);
            vals_i__ = context__.vals_i("Nv");
            pos__ = 0;
            Nv = vals_i__[pos__++];
            check_greater_or_equal(function__, "Nv", Nv, 1);
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "Ne", "int", context__.to_vec());
            Ne = int(0);
            vals_i__ = context__.vals_i("Ne");
            pos__ = 0;
            Ne = vals_i__[pos__++];
            check_greater_or_equal(function__, "Ne", Ne, 1);
            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "Ny", "int", context__.to_vec());
            Ny = int(0);
            vals_i__ = context__.vals_i("Ny");
            pos__ = 0;
            Ny = vals_i__[pos__++];
            check_greater_or_equal(function__, "Ny", Ny, 1);
            current_statement_begin__ = 8;
            validate_non_negative_index("idyi", "(K - Ny)", (K - Ny));
            context__.validate_dims("data initialization", "idyi", "int", context__.to_vec((K - Ny)));
            idyi = std::vector<int>((K - Ny), int(0));
            vals_i__ = context__.vals_i("idyi");
            pos__ = 0;
            size_t idyi_k_0_max__ = (K - Ny);
            for (size_t k_0__ = 0; k_0__ < idyi_k_0_max__; ++k_0__) {
                idyi[k_0__] = vals_i__[pos__++];
            }
            size_t idyi_i_0_max__ = (K - Ny);
            for (size_t i_0__ = 0; i_0__ < idyi_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "idyi[i_0__]", idyi[i_0__], 1);
            }
            current_statement_begin__ = 9;
            validate_non_negative_index("idy", "Ny", Ny);
            context__.validate_dims("data initialization", "idy", "int", context__.to_vec(Ny));
            idy = std::vector<int>(Ny, int(0));
            vals_i__ = context__.vals_i("idy");
            pos__ = 0;
            size_t idy_k_0_max__ = Ny;
            for (size_t k_0__ = 0; k_0__ < idy_k_0_max__; ++k_0__) {
                idy[k_0__] = vals_i__[pos__++];
            }
            size_t idy_i_0_max__ = Ny;
            for (size_t i_0__ = 0; i_0__ < idy_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "idy[i_0__]", idy[i_0__], 1);
            }
            current_statement_begin__ = 10;
            validate_non_negative_index("nbeta", "Ny", Ny);
            context__.validate_dims("data initialization", "nbeta", "int", context__.to_vec(Ny));
            nbeta = std::vector<int>(Ny, int(0));
            vals_i__ = context__.vals_i("nbeta");
            pos__ = 0;
            size_t nbeta_k_0_max__ = Ny;
            for (size_t k_0__ = 0; k_0__ < nbeta_k_0_max__; ++k_0__) {
                nbeta[k_0__] = vals_i__[pos__++];
            }
            size_t nbeta_i_0_max__ = Ny;
            for (size_t i_0__ = 0; i_0__ < nbeta_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "nbeta[i_0__]", nbeta[i_0__], 1);
            }
            current_statement_begin__ = 11;
            validate_non_negative_index("idlamb", "sum(nbeta)", sum(nbeta));
            context__.validate_dims("data initialization", "idlamb", "int", context__.to_vec(sum(nbeta)));
            idlamb = std::vector<int>(sum(nbeta), int(0));
            vals_i__ = context__.vals_i("idlamb");
            pos__ = 0;
            size_t idlamb_k_0_max__ = sum(nbeta);
            for (size_t k_0__ = 0; k_0__ < idlamb_k_0_max__; ++k_0__) {
                idlamb[k_0__] = vals_i__[pos__++];
            }
            size_t idlamb_i_0_max__ = sum(nbeta);
            for (size_t i_0__ = 0; i_0__ < idlamb_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "idlamb[i_0__]", idlamb[i_0__], 1);
            }
            current_statement_begin__ = 13;
            context__.validate_dims("data initialization", "Nob", "int", context__.to_vec());
            Nob = int(0);
            vals_i__ = context__.vals_i("Nob");
            pos__ = 0;
            Nob = vals_i__[pos__++];
            check_greater_or_equal(function__, "Nob", Nob, 1);
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "Nna", "int", context__.to_vec());
            Nna = int(0);
            vals_i__ = context__.vals_i("Nna");
            pos__ = 0;
            Nna = vals_i__[pos__++];
            check_greater_or_equal(function__, "Nna", Nna, 1);
            current_statement_begin__ = 15;
            validate_non_negative_index("X", "Nv", Nv);
            validate_non_negative_index("X", "Ne", Ne);
            context__.validate_dims("data initialization", "X", "matrix_d", context__.to_vec(Nv,Ne));
            X = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(Nv, Ne);
            vals_r__ = context__.vals_r("X");
            pos__ = 0;
            size_t X_j_2_max__ = Ne;
            size_t X_j_1_max__ = Nv;
            for (size_t j_2__ = 0; j_2__ < X_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < X_j_1_max__; ++j_1__) {
                    X(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 16;
            validate_non_negative_index("idob", "Nob", Nob);
            validate_non_negative_index("idob", "2", 2);
            context__.validate_dims("data initialization", "idob", "int", context__.to_vec(Nob,2));
            idob = std::vector<std::vector<int> >(Nob, std::vector<int>(2, int(0)));
            vals_i__ = context__.vals_i("idob");
            pos__ = 0;
            size_t idob_k_0_max__ = Nob;
            size_t idob_k_1_max__ = 2;
            for (size_t k_1__ = 0; k_1__ < idob_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < idob_k_0_max__; ++k_0__) {
                    idob[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            size_t idob_i_0_max__ = Nob;
            size_t idob_i_1_max__ = 2;
            for (size_t i_0__ = 0; i_0__ < idob_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < idob_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "idob[i_0__][i_1__]", idob[i_0__][i_1__], 1);
                }
            }
            current_statement_begin__ = 17;
            validate_non_negative_index("idna", "Nna", Nna);
            validate_non_negative_index("idna", "2", 2);
            context__.validate_dims("data initialization", "idna", "int", context__.to_vec(Nna,2));
            idna = std::vector<std::vector<int> >(Nna, std::vector<int>(2, int(0)));
            vals_i__ = context__.vals_i("idna");
            pos__ = 0;
            size_t idna_k_0_max__ = Nna;
            size_t idna_k_1_max__ = 2;
            for (size_t k_1__ = 0; k_1__ < idna_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < idna_k_0_max__; ++k_0__) {
                    idna[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            size_t idna_i_0_max__ = Nna;
            size_t idna_i_1_max__ = 2;
            for (size_t i_0__ = 0; i_0__ < idna_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < idna_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "idna[i_0__][i_1__]", idna[i_0__][i_1__], 1);
                }
            }
            current_statement_begin__ = 19;
            context__.validate_dims("data initialization", "Nex", "int", context__.to_vec());
            Nex = int(0);
            vals_i__ = context__.vals_i("Nex");
            pos__ = 0;
            Nex = vals_i__[pos__++];
            check_greater_or_equal(function__, "Nex", Nex, 1);
            current_statement_begin__ = 20;
            validate_non_negative_index("ngamma", "Nex", Nex);
            context__.validate_dims("data initialization", "ngamma", "int", context__.to_vec(Nex));
            ngamma = std::vector<int>(Nex, int(0));
            vals_i__ = context__.vals_i("ngamma");
            pos__ = 0;
            size_t ngamma_k_0_max__ = Nex;
            for (size_t k_0__ = 0; k_0__ < ngamma_k_0_max__; ++k_0__) {
                ngamma[k_0__] = vals_i__[pos__++];
            }
            size_t ngamma_i_0_max__ = Nex;
            for (size_t i_0__ = 0; i_0__ < ngamma_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "ngamma[i_0__]", ngamma[i_0__], 1);
            }
            current_statement_begin__ = 21;
            validate_non_negative_index("idexi", "sum(ngamma)", sum(ngamma));
            context__.validate_dims("data initialization", "idexi", "int", context__.to_vec(sum(ngamma)));
            idexi = std::vector<int>(sum(ngamma), int(0));
            vals_i__ = context__.vals_i("idexi");
            pos__ = 0;
            size_t idexi_k_0_max__ = sum(ngamma);
            for (size_t k_0__ = 0; k_0__ < idexi_k_0_max__; ++k_0__) {
                idexi[k_0__] = vals_i__[pos__++];
            }
            size_t idexi_i_0_max__ = sum(ngamma);
            for (size_t i_0__ = 0; i_0__ < idexi_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "idexi[i_0__]", idexi[i_0__], 1);
            }
            current_statement_begin__ = 22;
            validate_non_negative_index("idex", "Nex", Nex);
            context__.validate_dims("data initialization", "idex", "int", context__.to_vec(Nex));
            idex = std::vector<int>(Nex, int(0));
            vals_i__ = context__.vals_i("idex");
            pos__ = 0;
            size_t idex_k_0_max__ = Nex;
            for (size_t k_0__ = 0; k_0__ < idex_k_0_max__; ++k_0__) {
                idex[k_0__] = vals_i__[pos__++];
            }
            size_t idex_i_0_max__ = Nex;
            for (size_t i_0__ = 0; i_0__ < idex_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "idex[i_0__]", idex[i_0__], 1);
            }
            current_statement_begin__ = 23;
            validate_non_negative_index("idlambex", "sum(ngamma)", sum(ngamma));
            context__.validate_dims("data initialization", "idlambex", "int", context__.to_vec(sum(ngamma)));
            idlambex = std::vector<int>(sum(ngamma), int(0));
            vals_i__ = context__.vals_i("idlambex");
            pos__ = 0;
            size_t idlambex_k_0_max__ = sum(ngamma);
            for (size_t k_0__ = 0; k_0__ < idlambex_k_0_max__; ++k_0__) {
                idlambex[k_0__] = vals_i__[pos__++];
            }
            size_t idlambex_i_0_max__ = sum(ngamma);
            for (size_t i_0__ = 0; i_0__ < idlambex_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "idlambex[i_0__]", idlambex[i_0__], 1);
            }
            current_statement_begin__ = 25;
            validate_non_negative_index("asc", "Nob", Nob);
            context__.validate_dims("data initialization", "asc", "int", context__.to_vec(Nob));
            asc = std::vector<int>(Nob, int(0));
            vals_i__ = context__.vals_i("asc");
            pos__ = 0;
            size_t asc_k_0_max__ = Nob;
            for (size_t k_0__ = 0; k_0__ < asc_k_0_max__; ++k_0__) {
                asc[k_0__] = vals_i__[pos__++];
            }
            size_t asc_i_0_max__ = Nob;
            for (size_t i_0__ = 0; i_0__ < asc_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "asc[i_0__]", asc[i_0__], 1);
            }
            current_statement_begin__ = 26;
            validate_non_negative_index("v", "(Nv - Nex)", (Nv - Nex));
            validate_non_negative_index("v", "K", K);
            context__.validate_dims("data initialization", "v", "matrix_d", context__.to_vec((Nv - Nex),K));
            v = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>((Nv - Nex), K);
            vals_r__ = context__.vals_r("v");
            pos__ = 0;
            size_t v_j_2_max__ = K;
            size_t v_j_1_max__ = (Nv - Nex);
            for (size_t j_2__ = 0; j_2__ < v_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < v_j_1_max__; ++j_1__) {
                    v(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 29;
            validate_non_negative_index("dsigma2", "(Nv - Nex)", (Nv - Nex));
            context__.validate_dims("data initialization", "dsigma2", "double", context__.to_vec((Nv - Nex)));
            dsigma2 = std::vector<double>((Nv - Nex), double(0));
            vals_r__ = context__.vals_r("dsigma2");
            pos__ = 0;
            size_t dsigma2_k_0_max__ = (Nv - Nex);
            for (size_t k_0__ = 0; k_0__ < dsigma2_k_0_max__; ++k_0__) {
                dsigma2[k_0__] = vals_r__[pos__++];
            }
            size_t dsigma2_i_0_max__ = (Nv - Nex);
            for (size_t i_0__ = 0; i_0__ < dsigma2_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "dsigma2[i_0__]", dsigma2[i_0__], 0);
            }
            current_statement_begin__ = 30;
            validate_non_negative_index("a", "(Nv - Nex)", (Nv - Nex));
            context__.validate_dims("data initialization", "a", "double", context__.to_vec((Nv - Nex)));
            a = std::vector<double>((Nv - Nex), double(0));
            vals_r__ = context__.vals_r("a");
            pos__ = 0;
            size_t a_k_0_max__ = (Nv - Nex);
            for (size_t k_0__ = 0; k_0__ < a_k_0_max__; ++k_0__) {
                a[k_0__] = vals_r__[pos__++];
            }
            size_t a_i_0_max__ = (Nv - Nex);
            for (size_t i_0__ = 0; i_0__ < a_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "a[i_0__]", a[i_0__], 0);
            }
            current_statement_begin__ = 31;
            validate_non_negative_index("b", "(Nv - Nex)", (Nv - Nex));
            context__.validate_dims("data initialization", "b", "double", context__.to_vec((Nv - Nex)));
            b = std::vector<double>((Nv - Nex), double(0));
            vals_r__ = context__.vals_r("b");
            pos__ = 0;
            size_t b_k_0_max__ = (Nv - Nex);
            for (size_t k_0__ = 0; k_0__ < b_k_0_max__; ++k_0__) {
                b[k_0__] = vals_r__[pos__++];
            }
            size_t b_i_0_max__ = (Nv - Nex);
            for (size_t i_0__ = 0; i_0__ < b_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "b[i_0__]", b[i_0__], 0);
            }
            current_statement_begin__ = 32;
            validate_non_negative_index("dtau2", "Nex", Nex);
            context__.validate_dims("data initialization", "dtau2", "double", context__.to_vec(Nex));
            dtau2 = std::vector<double>(Nex, double(0));
            vals_r__ = context__.vals_r("dtau2");
            pos__ = 0;
            size_t dtau2_k_0_max__ = Nex;
            for (size_t k_0__ = 0; k_0__ < dtau2_k_0_max__; ++k_0__) {
                dtau2[k_0__] = vals_r__[pos__++];
            }
            size_t dtau2_i_0_max__ = Nex;
            for (size_t i_0__ = 0; i_0__ < dtau2_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "dtau2[i_0__]", dtau2[i_0__], 0);
            }
            current_statement_begin__ = 33;
            validate_non_negative_index("at", "Nex", Nex);
            context__.validate_dims("data initialization", "at", "double", context__.to_vec(Nex));
            at = std::vector<double>(Nex, double(0));
            vals_r__ = context__.vals_r("at");
            pos__ = 0;
            size_t at_k_0_max__ = Nex;
            for (size_t k_0__ = 0; k_0__ < at_k_0_max__; ++k_0__) {
                at[k_0__] = vals_r__[pos__++];
            }
            size_t at_i_0_max__ = Nex;
            for (size_t i_0__ = 0; i_0__ < at_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "at[i_0__]", at[i_0__], 0);
            }
            current_statement_begin__ = 34;
            validate_non_negative_index("bt", "Nex", Nex);
            context__.validate_dims("data initialization", "bt", "double", context__.to_vec(Nex));
            bt = std::vector<double>(Nex, double(0));
            vals_r__ = context__.vals_r("bt");
            pos__ = 0;
            size_t bt_k_0_max__ = Nex;
            for (size_t k_0__ = 0; k_0__ < bt_k_0_max__; ++k_0__) {
                bt[k_0__] = vals_r__[pos__++];
            }
            size_t bt_i_0_max__ = Nex;
            for (size_t i_0__ = 0; i_0__ < bt_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "bt[i_0__]", bt[i_0__], 0);
            }
            current_statement_begin__ = 36;
            validate_non_negative_index("dbeta", "sum(nbeta)", sum(nbeta));
            context__.validate_dims("data initialization", "dbeta", "double", context__.to_vec(sum(nbeta)));
            dbeta = std::vector<double>(sum(nbeta), double(0));
            vals_r__ = context__.vals_r("dbeta");
            pos__ = 0;
            size_t dbeta_k_0_max__ = sum(nbeta);
            for (size_t k_0__ = 0; k_0__ < dbeta_k_0_max__; ++k_0__) {
                dbeta[k_0__] = vals_r__[pos__++];
            }
            size_t dbeta_i_0_max__ = sum(nbeta);
            for (size_t i_0__ = 0; i_0__ < dbeta_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "dbeta[i_0__]", dbeta[i_0__], 0);
            }
            current_statement_begin__ = 37;
            validate_non_negative_index("m", "sum(nbeta)", sum(nbeta));
            context__.validate_dims("data initialization", "m", "double", context__.to_vec(sum(nbeta)));
            m = std::vector<double>(sum(nbeta), double(0));
            vals_r__ = context__.vals_r("m");
            pos__ = 0;
            size_t m_k_0_max__ = sum(nbeta);
            for (size_t k_0__ = 0; k_0__ < m_k_0_max__; ++k_0__) {
                m[k_0__] = vals_r__[pos__++];
            }
            size_t m_i_0_max__ = sum(nbeta);
            for (size_t i_0__ = 0; i_0__ < m_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "m[i_0__]", m[i_0__], 0);
            }
            current_statement_begin__ = 38;
            validate_non_negative_index("s", "sum(nbeta)", sum(nbeta));
            context__.validate_dims("data initialization", "s", "double", context__.to_vec(sum(nbeta)));
            s = std::vector<double>(sum(nbeta), double(0));
            vals_r__ = context__.vals_r("s");
            pos__ = 0;
            size_t s_k_0_max__ = sum(nbeta);
            for (size_t k_0__ = 0; k_0__ < s_k_0_max__; ++k_0__) {
                s[k_0__] = vals_r__[pos__++];
            }
            size_t s_i_0_max__ = sum(nbeta);
            for (size_t i_0__ = 0; i_0__ < s_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "s[i_0__]", s[i_0__], 0);
            }
            current_statement_begin__ = 39;
            validate_non_negative_index("dgamma", "sum(ngamma)", sum(ngamma));
            context__.validate_dims("data initialization", "dgamma", "double", context__.to_vec(sum(ngamma)));
            dgamma = std::vector<double>(sum(ngamma), double(0));
            vals_r__ = context__.vals_r("dgamma");
            pos__ = 0;
            size_t dgamma_k_0_max__ = sum(ngamma);
            for (size_t k_0__ = 0; k_0__ < dgamma_k_0_max__; ++k_0__) {
                dgamma[k_0__] = vals_r__[pos__++];
            }
            size_t dgamma_i_0_max__ = sum(ngamma);
            for (size_t i_0__ = 0; i_0__ < dgamma_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "dgamma[i_0__]", dgamma[i_0__], 0);
            }
            current_statement_begin__ = 40;
            validate_non_negative_index("mg", "sum(ngamma)", sum(ngamma));
            context__.validate_dims("data initialization", "mg", "double", context__.to_vec(sum(ngamma)));
            mg = std::vector<double>(sum(ngamma), double(0));
            vals_r__ = context__.vals_r("mg");
            pos__ = 0;
            size_t mg_k_0_max__ = sum(ngamma);
            for (size_t k_0__ = 0; k_0__ < mg_k_0_max__; ++k_0__) {
                mg[k_0__] = vals_r__[pos__++];
            }
            size_t mg_i_0_max__ = sum(ngamma);
            for (size_t i_0__ = 0; i_0__ < mg_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "mg[i_0__]", mg[i_0__], 0);
            }
            current_statement_begin__ = 41;
            validate_non_negative_index("sg", "sum(ngamma)", sum(ngamma));
            context__.validate_dims("data initialization", "sg", "double", context__.to_vec(sum(ngamma)));
            sg = std::vector<double>(sum(ngamma), double(0));
            vals_r__ = context__.vals_r("sg");
            pos__ = 0;
            size_t sg_k_0_max__ = sum(ngamma);
            for (size_t k_0__ = 0; k_0__ < sg_k_0_max__; ++k_0__) {
                sg[k_0__] = vals_r__[pos__++];
            }
            size_t sg_i_0_max__ = sum(ngamma);
            for (size_t i_0__ = 0; i_0__ < sg_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "sg[i_0__]", sg[i_0__], 0);
            }
            current_statement_begin__ = 42;
            validate_non_negative_index("dgamma0", "Nex", Nex);
            context__.validate_dims("data initialization", "dgamma0", "double", context__.to_vec(Nex));
            dgamma0 = std::vector<double>(Nex, double(0));
            vals_r__ = context__.vals_r("dgamma0");
            pos__ = 0;
            size_t dgamma0_k_0_max__ = Nex;
            for (size_t k_0__ = 0; k_0__ < dgamma0_k_0_max__; ++k_0__) {
                dgamma0[k_0__] = vals_r__[pos__++];
            }
            size_t dgamma0_i_0_max__ = Nex;
            for (size_t i_0__ = 0; i_0__ < dgamma0_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "dgamma0[i_0__]", dgamma0[i_0__], 0);
            }
            current_statement_begin__ = 43;
            validate_non_negative_index("mg0", "Nex", Nex);
            context__.validate_dims("data initialization", "mg0", "double", context__.to_vec(Nex));
            mg0 = std::vector<double>(Nex, double(0));
            vals_r__ = context__.vals_r("mg0");
            pos__ = 0;
            size_t mg0_k_0_max__ = Nex;
            for (size_t k_0__ = 0; k_0__ < mg0_k_0_max__; ++k_0__) {
                mg0[k_0__] = vals_r__[pos__++];
            }
            size_t mg0_i_0_max__ = Nex;
            for (size_t i_0__ = 0; i_0__ < mg0_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "mg0[i_0__]", mg0[i_0__], 0);
            }
            current_statement_begin__ = 44;
            validate_non_negative_index("sg0", "Nex", Nex);
            context__.validate_dims("data initialization", "sg0", "double", context__.to_vec(Nex));
            sg0 = std::vector<double>(Nex, double(0));
            vals_r__ = context__.vals_r("sg0");
            pos__ = 0;
            size_t sg0_k_0_max__ = Nex;
            for (size_t k_0__ = 0; k_0__ < sg0_k_0_max__; ++k_0__) {
                sg0[k_0__] = vals_r__[pos__++];
            }
            size_t sg0_i_0_max__ = Nex;
            for (size_t i_0__ = 0; i_0__ < sg0_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "sg0[i_0__]", sg0[i_0__], 0);
            }
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 48;
            validate_non_negative_index("alpha", "(Nv - Nex)", (Nv - Nex));
            validate_non_negative_index("alpha", "K", K);
            num_params_r__ += ((Nv - Nex) * K);
            current_statement_begin__ = 49;
            validate_non_negative_index("lambda", "K", K);
            validate_non_negative_index("lambda", "Ne", Ne);
            num_params_r__ += (K * Ne);
            current_statement_begin__ = 50;
            validate_non_negative_index("sigma2", "(Nv - Nex)", (Nv - Nex));
            num_params_r__ += (Nv - Nex);
            current_statement_begin__ = 51;
            validate_non_negative_index("Xna", "Nna", Nna);
            num_params_r__ += Nna;
            current_statement_begin__ = 53;
            validate_non_negative_index("beta", "sum(nbeta)", sum(nbeta));
            num_params_r__ += sum(nbeta);
            current_statement_begin__ = 55;
            validate_non_negative_index("gamma0", "Nex", Nex);
            num_params_r__ += Nex;
            current_statement_begin__ = 56;
            validate_non_negative_index("gamma", "sum(ngamma)", sum(ngamma));
            num_params_r__ += sum(ngamma);
            current_statement_begin__ = 57;
            validate_non_negative_index("tau2", "Nex", Nex);
            num_params_r__ += Nex;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_semNAEX() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 48;
        if (!(context__.contains_r("alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha");
        pos__ = 0U;
        validate_non_negative_index("alpha", "(Nv - Nex)", (Nv - Nex));
        validate_non_negative_index("alpha", "K", K);
        context__.validate_dims("parameter initialization", "alpha", "matrix_d", context__.to_vec((Nv - Nex),K));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> alpha((Nv - Nex), K);
        size_t alpha_j_2_max__ = K;
        size_t alpha_j_1_max__ = (Nv - Nex);
        for (size_t j_2__ = 0; j_2__ < alpha_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
                alpha(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.matrix_unconstrain(alpha);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 49;
        if (!(context__.contains_r("lambda")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda");
        pos__ = 0U;
        validate_non_negative_index("lambda", "K", K);
        validate_non_negative_index("lambda", "Ne", Ne);
        context__.validate_dims("parameter initialization", "lambda", "matrix_d", context__.to_vec(K,Ne));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> lambda(K, Ne);
        size_t lambda_j_2_max__ = Ne;
        size_t lambda_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < lambda_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
                lambda(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.matrix_unconstrain(lambda);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 50;
        if (!(context__.contains_r("sigma2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma2");
        pos__ = 0U;
        validate_non_negative_index("sigma2", "(Nv - Nex)", (Nv - Nex));
        context__.validate_dims("parameter initialization", "sigma2", "vector_d", context__.to_vec((Nv - Nex)));
        Eigen::Matrix<double, Eigen::Dynamic, 1> sigma2((Nv - Nex));
        size_t sigma2_j_1_max__ = (Nv - Nex);
        for (size_t j_1__ = 0; j_1__ < sigma2_j_1_max__; ++j_1__) {
            sigma2(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, sigma2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 51;
        if (!(context__.contains_r("Xna")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable Xna missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("Xna");
        pos__ = 0U;
        validate_non_negative_index("Xna", "Nna", Nna);
        context__.validate_dims("parameter initialization", "Xna", "vector_d", context__.to_vec(Nna));
        Eigen::Matrix<double, Eigen::Dynamic, 1> Xna(Nna);
        size_t Xna_j_1_max__ = Nna;
        for (size_t j_1__ = 0; j_1__ < Xna_j_1_max__; ++j_1__) {
            Xna(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(Xna);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable Xna: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 53;
        if (!(context__.contains_r("beta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta");
        pos__ = 0U;
        validate_non_negative_index("beta", "sum(nbeta)", sum(nbeta));
        context__.validate_dims("parameter initialization", "beta", "row_vector_d", context__.to_vec(sum(nbeta)));
        Eigen::Matrix<double, 1, Eigen::Dynamic> beta(sum(nbeta));
        size_t beta_j_1_max__ = sum(nbeta);
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            beta(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.row_vector_unconstrain(beta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 55;
        if (!(context__.contains_r("gamma0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable gamma0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("gamma0");
        pos__ = 0U;
        validate_non_negative_index("gamma0", "Nex", Nex);
        context__.validate_dims("parameter initialization", "gamma0", "row_vector_d", context__.to_vec(Nex));
        Eigen::Matrix<double, 1, Eigen::Dynamic> gamma0(Nex);
        size_t gamma0_j_1_max__ = Nex;
        for (size_t j_1__ = 0; j_1__ < gamma0_j_1_max__; ++j_1__) {
            gamma0(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.row_vector_unconstrain(gamma0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable gamma0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 56;
        if (!(context__.contains_r("gamma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable gamma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("gamma");
        pos__ = 0U;
        validate_non_negative_index("gamma", "sum(ngamma)", sum(ngamma));
        context__.validate_dims("parameter initialization", "gamma", "row_vector_d", context__.to_vec(sum(ngamma)));
        Eigen::Matrix<double, 1, Eigen::Dynamic> gamma(sum(ngamma));
        size_t gamma_j_1_max__ = sum(ngamma);
        for (size_t j_1__ = 0; j_1__ < gamma_j_1_max__; ++j_1__) {
            gamma(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.row_vector_unconstrain(gamma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable gamma: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 57;
        if (!(context__.contains_r("tau2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable tau2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("tau2");
        pos__ = 0U;
        validate_non_negative_index("tau2", "Nex", Nex);
        context__.validate_dims("parameter initialization", "tau2", "row_vector_d", context__.to_vec(Nex));
        Eigen::Matrix<double, 1, Eigen::Dynamic> tau2(Nex);
        size_t tau2_j_1_max__ = Nex;
        for (size_t j_1__ = 0; j_1__ < tau2_j_1_max__; ++j_1__) {
            tau2(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.row_vector_lb_unconstrain(0, tau2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable tau2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 48;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> alpha;
            (void) alpha;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha = in__.matrix_constrain((Nv - Nex), K, lp__);
            else
                alpha = in__.matrix_constrain((Nv - Nex), K);
            current_statement_begin__ = 49;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> lambda;
            (void) lambda;  // dummy to suppress unused var warning
            if (jacobian__)
                lambda = in__.matrix_constrain(K, Ne, lp__);
            else
                lambda = in__.matrix_constrain(K, Ne);
            current_statement_begin__ = 50;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> sigma2;
            (void) sigma2;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma2 = in__.vector_lb_constrain(0, (Nv - Nex), lp__);
            else
                sigma2 = in__.vector_lb_constrain(0, (Nv - Nex));
            current_statement_begin__ = 51;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> Xna;
            (void) Xna;  // dummy to suppress unused var warning
            if (jacobian__)
                Xna = in__.vector_constrain(Nna, lp__);
            else
                Xna = in__.vector_constrain(Nna);
            current_statement_begin__ = 53;
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> beta;
            (void) beta;  // dummy to suppress unused var warning
            if (jacobian__)
                beta = in__.row_vector_constrain(sum(nbeta), lp__);
            else
                beta = in__.row_vector_constrain(sum(nbeta));
            current_statement_begin__ = 55;
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> gamma0;
            (void) gamma0;  // dummy to suppress unused var warning
            if (jacobian__)
                gamma0 = in__.row_vector_constrain(Nex, lp__);
            else
                gamma0 = in__.row_vector_constrain(Nex);
            current_statement_begin__ = 56;
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> gamma;
            (void) gamma;  // dummy to suppress unused var warning
            if (jacobian__)
                gamma = in__.row_vector_constrain(sum(ngamma), lp__);
            else
                gamma = in__.row_vector_constrain(sum(ngamma));
            current_statement_begin__ = 57;
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> tau2;
            (void) tau2;  // dummy to suppress unused var warning
            if (jacobian__)
                tau2 = in__.row_vector_lb_constrain(0, Nex, lp__);
            else
                tau2 = in__.row_vector_lb_constrain(0, Nex);
            // model body
            current_statement_begin__ = 62;
            for (int i = 1; i <= Nob; ++i) {
                current_statement_begin__ = 63;
                lp_accum__.add(normal_log<propto__>(get_base1(X, get_base1(get_base1(idob, i, "idob", 1), 1, "idob", 2), get_base1(get_base1(idob, i, "idob", 1), 2, "idob", 2), "X", 1), multiply(stan::model::rvalue(alpha, stan::model::cons_list(stan::model::index_uni((get_base1(asc, i, "asc", 1) - Nex)), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "alpha"), stan::model::rvalue(lambda, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(get_base1(get_base1(idob, i, "idob", 1), 2, "idob", 2)), stan::model::nil_index_list())), "lambda")), stan::math::sqrt(get_base1(sigma2, get_base1(asc, i, "asc", 1), "sigma2", 1))));
            }
            current_statement_begin__ = 67;
            for (int k = 1; k <= K; ++k) {
                current_statement_begin__ = 68;
                lp_accum__.add(normal_log<propto__>(stan::model::rvalue(alpha, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list())), "alpha"), 0, stan::math::sqrt(stan::model::rvalue(v, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list())), "v"))));
            }
            current_statement_begin__ = 71;
            lp_accum__.add(normal_log<propto__>(stan::model::rvalue(lambda, stan::model::cons_list(stan::model::index_uni(get_base1(idy, 1, "idy", 1)), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "lambda"), multiply(stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_min_max(1, get_base1(nbeta, 1, "nbeta", 1)), stan::model::nil_index_list()), "beta"), stan::model::rvalue(lambda, stan::model::cons_list(stan::model::index_multi(stan::model::rvalue(idlamb, stan::model::cons_list(stan::model::index_min_max(1, get_base1(nbeta, 1, "nbeta", 1)), stan::model::nil_index_list()), "idlamb")), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "lambda")), 1));
            current_statement_begin__ = 73;
            if (as_bool(logical_gt(Ny, 1))) {
                current_statement_begin__ = 74;
                for (int i = 2; i <= Ny; ++i) {
                    current_statement_begin__ = 75;
                    lp_accum__.add(normal_log<propto__>(stan::model::rvalue(lambda, stan::model::cons_list(stan::model::index_uni(get_base1(idy, i, "idy", 1)), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "lambda"), multiply(stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_min_max((sum(stan::model::rvalue(nbeta, stan::model::cons_list(stan::model::index_min_max(1, (i - 1)), stan::model::nil_index_list()), "nbeta")) + 1), sum(stan::model::rvalue(nbeta, stan::model::cons_list(stan::model::index_min_max(1, i), stan::model::nil_index_list()), "nbeta"))), stan::model::nil_index_list()), "beta"), stan::model::rvalue(lambda, stan::model::cons_list(stan::model::index_multi(stan::model::rvalue(idlamb, stan::model::cons_list(stan::model::index_min_max((sum(stan::model::rvalue(nbeta, stan::model::cons_list(stan::model::index_min_max(1, (i - 1)), stan::model::nil_index_list()), "nbeta")) + 1), sum(stan::model::rvalue(nbeta, stan::model::cons_list(stan::model::index_min_max(1, i), stan::model::nil_index_list()), "nbeta"))), stan::model::nil_index_list()), "idlamb")), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "lambda")), 1));
                }
            }
            current_statement_begin__ = 80;
            lp_accum__.add(normal_log<propto__>(to_vector(stan::model::rvalue(lambda, stan::model::cons_list(stan::model::index_multi(idyi), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "lambda")), 0, 1));
            current_statement_begin__ = 84;
            lp_accum__.add(normal_log<propto__>(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(get_base1(idex, 1, "idex", 1)), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"), add(get_base1(gamma0, 1, "gamma0", 1), multiply(stan::model::rvalue(gamma, stan::model::cons_list(stan::model::index_min_max(1, get_base1(ngamma, 1, "ngamma", 1)), stan::model::nil_index_list()), "gamma"), stan::model::rvalue(lambda, stan::model::cons_list(stan::model::index_multi(stan::model::rvalue(idlambex, stan::model::cons_list(stan::model::index_min_max(1, get_base1(ngamma, 1, "ngamma", 1)), stan::model::nil_index_list()), "idlambex")), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "lambda"))), get_base1(tau2, 1, "tau2", 1)));
            current_statement_begin__ = 86;
            if (as_bool(logical_gt(Nex, 1))) {
                current_statement_begin__ = 87;
                for (int i = 2; i <= Nex; ++i) {
                    current_statement_begin__ = 88;
                    lp_accum__.add(normal_log<propto__>(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(get_base1(idex, i, "idex", 1)), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"), add(get_base1(gamma0, i, "gamma0", 1), multiply(stan::model::rvalue(gamma, stan::model::cons_list(stan::model::index_min_max((sum(stan::model::rvalue(ngamma, stan::model::cons_list(stan::model::index_min_max(1, (i - 1)), stan::model::nil_index_list()), "ngamma")) + 1), sum(stan::model::rvalue(ngamma, stan::model::cons_list(stan::model::index_min_max(1, i), stan::model::nil_index_list()), "ngamma"))), stan::model::nil_index_list()), "gamma"), stan::model::rvalue(lambda, stan::model::cons_list(stan::model::index_multi(stan::model::rvalue(idlambex, stan::model::cons_list(stan::model::index_min_max((sum(stan::model::rvalue(ngamma, stan::model::cons_list(stan::model::index_min_max(1, (i - 1)), stan::model::nil_index_list()), "ngamma")) + 1), sum(stan::model::rvalue(ngamma, stan::model::cons_list(stan::model::index_min_max(1, i), stan::model::nil_index_list()), "ngamma"))), stan::model::nil_index_list()), "idlambex")), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "lambda"))), get_base1(tau2, i, "tau2", 1)));
                }
            }
            current_statement_begin__ = 93;
            for (int i = 1; i <= Nna; ++i) {
                current_statement_begin__ = 94;
                lp_accum__.add(normal_log<propto__>(get_base1(Xna, i, "Xna", 1), multiply(stan::model::rvalue(alpha, stan::model::cons_list(stan::model::index_uni(get_base1(get_base1(idna, i, "idna", 1), 1, "idna", 2)), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "alpha"), stan::model::rvalue(lambda, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(get_base1(get_base1(idna, i, "idna", 1), 2, "idna", 2)), stan::model::nil_index_list())), "lambda")), stan::math::sqrt(get_base1(sigma2, get_base1(get_base1(idna, i, "idna", 1), 1, "idna", 2), "sigma2", 1))));
            }
            current_statement_begin__ = 97;
            for (int i = 1; i <= (Nv - Nex); ++i) {
                current_statement_begin__ = 99;
                if (as_bool(logical_eq(get_base1(dsigma2, i, "dsigma2", 1), 0))) {
                    current_statement_begin__ = 100;
                    lp_accum__.add(gamma_log<propto__>(get_base1(sigma2, i, "sigma2", 1), get_base1(a, i, "a", 1), get_base1(b, i, "b", 1)));
                } else if (as_bool(logical_eq(get_base1(dsigma2, i, "dsigma2", 1), 1))) {
                    current_statement_begin__ = 103;
                    lp_accum__.add(inv_gamma_log<propto__>(get_base1(sigma2, i, "sigma2", 1), get_base1(a, i, "a", 1), get_base1(b, i, "b", 1)));
                } else {
                    current_statement_begin__ = 106;
                    lp_accum__.add(lognormal_log<propto__>(get_base1(sigma2, i, "sigma2", 1), get_base1(a, i, "a", 1), get_base1(b, i, "b", 1)));
                }
            }
            current_statement_begin__ = 109;
            for (int i = 1; i <= Nex; ++i) {
                current_statement_begin__ = 111;
                if (as_bool(logical_eq(get_base1(dtau2, i, "dtau2", 1), 0))) {
                    current_statement_begin__ = 112;
                    lp_accum__.add(gamma_log<propto__>(get_base1(tau2, i, "tau2", 1), get_base1(at, i, "at", 1), get_base1(bt, i, "bt", 1)));
                } else if (as_bool(logical_eq(get_base1(dtau2, i, "dtau2", 1), 1))) {
                    current_statement_begin__ = 115;
                    lp_accum__.add(inv_gamma_log<propto__>(get_base1(tau2, i, "tau2", 1), get_base1(at, i, "at", 1), get_base1(bt, i, "bt", 1)));
                } else {
                    current_statement_begin__ = 118;
                    lp_accum__.add(lognormal_log<propto__>(get_base1(tau2, i, "tau2", 1), get_base1(at, i, "at", 1), get_base1(bt, i, "bt", 1)));
                }
            }
            current_statement_begin__ = 121;
            for (int i = 1; i <= sum(nbeta); ++i) {
                current_statement_begin__ = 123;
                if (as_bool(logical_eq(get_base1(dbeta, i, "dbeta", 1), 0))) {
                    current_statement_begin__ = 124;
                    lp_accum__.add(normal_log<propto__>(get_base1(beta, i, "beta", 1), get_base1(m, i, "m", 1), stan::math::sqrt(get_base1(s, i, "s", 1))));
                } else {
                    current_statement_begin__ = 127;
                    lp_accum__.add(cauchy_log<propto__>(get_base1(beta, i, "beta", 1), get_base1(m, i, "m", 1), stan::math::sqrt(get_base1(s, i, "s", 1))));
                }
            }
            current_statement_begin__ = 131;
            for (int i = 1; i <= Nex; ++i) {
                current_statement_begin__ = 132;
                if (as_bool(logical_eq(get_base1(dgamma0, i, "dgamma0", 1), 0))) {
                    current_statement_begin__ = 133;
                    lp_accum__.add(normal_log<propto__>(get_base1(gamma0, i, "gamma0", 1), get_base1(mg0, i, "mg0", 1), stan::math::sqrt(get_base1(sg0, i, "sg0", 1))));
                } else {
                    current_statement_begin__ = 136;
                    lp_accum__.add(cauchy_log<propto__>(get_base1(gamma0, i, "gamma0", 1), get_base1(mg0, i, "mg0", 1), stan::math::sqrt(get_base1(sg0, i, "sg0", 1))));
                }
            }
            current_statement_begin__ = 141;
            for (int i = 1; i <= sum(ngamma); ++i) {
                current_statement_begin__ = 142;
                if (as_bool(logical_eq(get_base1(dgamma, i, "dgamma", 1), 0))) {
                    current_statement_begin__ = 143;
                    lp_accum__.add(normal_log<propto__>(get_base1(gamma, i, "gamma", 1), get_base1(mg, i, "mg", 1), stan::math::sqrt(get_base1(sg, i, "sg", 1))));
                } else {
                    current_statement_begin__ = 146;
                    lp_accum__.add(cauchy_log<propto__>(get_base1(gamma, i, "gamma", 1), get_base1(mg, i, "mg", 1), stan::math::sqrt(get_base1(sg, i, "sg", 1))));
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("alpha");
        names__.push_back("lambda");
        names__.push_back("sigma2");
        names__.push_back("Xna");
        names__.push_back("beta");
        names__.push_back("gamma0");
        names__.push_back("gamma");
        names__.push_back("tau2");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back((Nv - Nex));
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(Ne);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((Nv - Nex));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nna);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(sum(nbeta));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nex);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(sum(ngamma));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nex);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_semNAEX_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> alpha = in__.matrix_constrain((Nv - Nex), K);
        size_t alpha_j_2_max__ = K;
        size_t alpha_j_1_max__ = (Nv - Nex);
        for (size_t j_2__ = 0; j_2__ < alpha_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
                vars__.push_back(alpha(j_1__, j_2__));
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> lambda = in__.matrix_constrain(K, Ne);
        size_t lambda_j_2_max__ = Ne;
        size_t lambda_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < lambda_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
                vars__.push_back(lambda(j_1__, j_2__));
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> sigma2 = in__.vector_lb_constrain(0, (Nv - Nex));
        size_t sigma2_j_1_max__ = (Nv - Nex);
        for (size_t j_1__ = 0; j_1__ < sigma2_j_1_max__; ++j_1__) {
            vars__.push_back(sigma2(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> Xna = in__.vector_constrain(Nna);
        size_t Xna_j_1_max__ = Nna;
        for (size_t j_1__ = 0; j_1__ < Xna_j_1_max__; ++j_1__) {
            vars__.push_back(Xna(j_1__));
        }
        Eigen::Matrix<double, 1, Eigen::Dynamic> beta = in__.row_vector_constrain(sum(nbeta));
        size_t beta_j_1_max__ = sum(nbeta);
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            vars__.push_back(beta(j_1__));
        }
        Eigen::Matrix<double, 1, Eigen::Dynamic> gamma0 = in__.row_vector_constrain(Nex);
        size_t gamma0_j_1_max__ = Nex;
        for (size_t j_1__ = 0; j_1__ < gamma0_j_1_max__; ++j_1__) {
            vars__.push_back(gamma0(j_1__));
        }
        Eigen::Matrix<double, 1, Eigen::Dynamic> gamma = in__.row_vector_constrain(sum(ngamma));
        size_t gamma_j_1_max__ = sum(ngamma);
        for (size_t j_1__ = 0; j_1__ < gamma_j_1_max__; ++j_1__) {
            vars__.push_back(gamma(j_1__));
        }
        Eigen::Matrix<double, 1, Eigen::Dynamic> tau2 = in__.row_vector_lb_constrain(0, Nex);
        size_t tau2_j_1_max__ = Nex;
        for (size_t j_1__ = 0; j_1__ < tau2_j_1_max__; ++j_1__) {
            vars__.push_back(tau2(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_semNAEX";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t alpha_j_2_max__ = K;
        size_t alpha_j_1_max__ = (Nv - Nex);
        for (size_t j_2__ = 0; j_2__ < alpha_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "alpha" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t lambda_j_2_max__ = Ne;
        size_t lambda_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < lambda_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lambda" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t sigma2_j_1_max__ = (Nv - Nex);
        for (size_t j_1__ = 0; j_1__ < sigma2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t Xna_j_1_max__ = Nna;
        for (size_t j_1__ = 0; j_1__ < Xna_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Xna" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_j_1_max__ = sum(nbeta);
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t gamma0_j_1_max__ = Nex;
        for (size_t j_1__ = 0; j_1__ < gamma0_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gamma0" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t gamma_j_1_max__ = sum(ngamma);
        for (size_t j_1__ = 0; j_1__ < gamma_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gamma" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t tau2_j_1_max__ = Nex;
        for (size_t j_1__ = 0; j_1__ < tau2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "tau2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t alpha_j_2_max__ = K;
        size_t alpha_j_1_max__ = (Nv - Nex);
        for (size_t j_2__ = 0; j_2__ < alpha_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "alpha" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t lambda_j_2_max__ = Ne;
        size_t lambda_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < lambda_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lambda" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t sigma2_j_1_max__ = (Nv - Nex);
        for (size_t j_1__ = 0; j_1__ < sigma2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t Xna_j_1_max__ = Nna;
        for (size_t j_1__ = 0; j_1__ < Xna_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Xna" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_j_1_max__ = sum(nbeta);
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t gamma0_j_1_max__ = Nex;
        for (size_t j_1__ = 0; j_1__ < gamma0_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gamma0" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t gamma_j_1_max__ = sum(ngamma);
        for (size_t j_1__ = 0; j_1__ < gamma_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gamma" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t tau2_j_1_max__ = Nex;
        for (size_t j_1__ = 0; j_1__ < tau2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "tau2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_semNAEX_namespace::model_semNAEX stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
